Update like_util.py, potency_ratio = None
potency_ratio=None causes error when used with interact_with_user #1910

Traceback (most recent call last):
  File "quickstart.py", line 45, in <module>
    session.interact_by_users(users[:2], amount=1)
  File "C:\Users\marti\OneDrive\Proj\InstaPy-master\instapy\instapy.py", line 1307, in interact_by_users
    self.logger)
  File "C:\Users\marti\OneDrive\Proj\InstaPy-master\instapy\like_util.py", line 551, in check_link
    if potency_ratio < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'