Changed XPath in like_util.py to be more precise. Fixing an issue that caused Selemium to not find the "like/unlike" button after the 89753ae commit.
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <span class="_8scx2 coreSpriteHeartOpen">...</span> is not clickable at point (49, 588).
Other element would receive the click: <div class="_3dy6p">...</div>